server:
  port: 8082

spring:
  application:
    name: api-gateway-oauth2
  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: DS6wwP6M4YARCNEaeWeefRrXs2Aa
            client-secret: rit6pNZEXE23XmBVzrjFJmHGKGka
            provider: wso2
            clientAuthenticationMethod: basic
            scope: openid
            authorizationGrantType: authorization_code
            redirectUriTemplate: http://localhost:8082/login/oauth2/code/wso2
            clientName: api-gateway
        provider:
           wso2:
            authorizationUri: https://localhost:9443/oauth2/authorize
            tokenUri:  https://localhost:9443/oauth2/token
            userInfoUri: https://localhost:9443/oauth2/userinfo
            jwkSetUri: https://localhost:9443/oauth2/jwks
            userNameAttribute: name

logging:
  level:
    org:
      springframework:
        security: debug
